[2025-03-27T18:40:01.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T18:40:01.416+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:35:00+00:00 [queued]>
[2025-03-27T18:40:01.427+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:35:00+00:00 [queued]>
[2025-03-27T18:40:01.428+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-27T18:40:01.443+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): set_stage> on 2025-03-27 18:35:00+00:00
[2025-03-27T18:40:01.452+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=389) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T18:40:01.454+0000] {standard_task_runner.py:72} INFO - Started process 395 to run task
[2025-03-27T18:40:01.452+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'set_stage', 'scheduled__2025-03-27T18:35:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/HW6_ETL.py', '--cfg-path', '/tmp/tmpuptfzqhr']
[2025-03-27T18:40:01.455+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask set_stage
[2025-03-27T18:40:02.786+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL.set_stage scheduled__2025-03-27T18:35:00+00:00 [running]> on host 00cc07a75964
[2025-03-27T18:40:05.412+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='set_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T18:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T18:35:00+00:00'
[2025-03-27T18:40:05.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T18:40:05.436+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-27T18:40:05.438+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-03-27T18:40:05.439+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-27T18:40:05.440+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-27T18:40:06.529+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:40:06.664+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:40:06.812+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:40:07.094+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:40:07.297+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-27T18:40:07.298+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-27T18:40:07.309+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T18:40:07.310+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=set_stage, run_id=scheduled__2025-03-27T18:35:00+00:00, execution_date=20250327T183500, start_date=20250327T184001, end_date=20250327T184007
[2025-03-27T18:40:07.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-27T18:40:07.374+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T18:40:07.376+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
